<?php
define('KMS_LOGIN_PAGE_PRODUCT_LISTING', 'node/2');
define('KMS_LOGIN_PAGE_PRODUCT_DOWNLOADS', 'node/23');

/**
 * Implements hook_init().
 */
function kms_login_init() {
  /*
   * When a new user has received a confirmation mail with a one-time-login-url, or
   * an existing user has received a forgotten-password-mail the user will be sent
   * to /user/reset/%UID/%TIME/%TOKEN, to /user/reset/%UID/%TIME/%TOKEN/login, and
   * finally the function in user.pages.inc will call this drupal_goto:
   * drupal_goto('user/' . $user->uid . '/edit', array('query' => array('pass-reset-token' => $token)));
   *
   * But we would rather have the user going to /edit/profile?pass-reset-token=%TOKEN
   */
  if (arg(0) == 'user') {
    if (is_numeric(arg(1)) && arg(2) == 'edit') {
      // This is a URL of type /user/$account_uid/edit?pass-reset-token=TOKEN-VALUE
      // We must only redirect these requests if the current user equals the 
      // user being edited:
      global $user;
      if ($user->uid == arg(1)) {
        $token = (isset($_REQUEST['pass-reset-token'])) ? $_REQUEST['pass-reset-token'] : FALSE;
        if ($token) {
          drupal_goto("edit/profile", array('query' => array('pass-reset-token' => $token)));
        }
        else {
          drupal_goto("edit/profile");
        }
      }
    }
  }

  // Add data to JS settings. We'll pick this up in
  // gtm.js
  if (!empty($_SESSION['kms_login'])) {
    $gtm_type = _kms_user_get_user_type();
    $gtm_type = implode(' > ', $gtm_type);
    $origin = 'download.kortforsyningen.dk';

    // If the page is iframed add extra param
    // @see kms_iframe_test() but module is disabled atm
    $path = current_path();
    $match = 'iframe';
    if (substr_compare($path, $match, strlen($path)-strlen($match), strlen($match)) === 0) {
      $origin = 'kortforsyningen.dk';
    }

    drupal_add_js(drupal_get_path('module', 'kms_login') . '/js/gtm.js', 'file');
    drupal_add_js(array(
      'kms_login' => array(
        'type' => $gtm_type,
        'site' => $origin,
      )
    ), 'setting');

    $_SESSION['kms_login'] = FALSE;
  }

}

function kms_login_ctools_plugin_directory($owner, $plugin_type) {
  // we'll be nice and limit scandir() calls
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Implements hook_user_login().
 */
function kms_login_user_login(&$edit, $account) {

  // Add flag to check for in hook_init(). Cannot add to JS here due to
  // redirects
  $_SESSION['kms_login'] = TRUE;

  //
  if (empty($_POST['form_id'])) {
    return;
  }

  // Redirect to product list, if logging in from the front page
  // or the /user page

  if ( drupal_is_front_page() || arg(0) == 'login' ) {
    $redirect = variable_get( 'kms_login_page_product_listing', KMS_LOGIN_PAGE_PRODUCT_LISTING);
    $_GET['destination'] = $redirect; // Should we use $edit['redirect'] instead..?
  }
}

function kms_login_form_commerce_checkout_form_login_alter(&$form, &$form_state) {
  $form["login_pane"]['#title'] = '';
  $form["login_pane"]['#description'] = t('You must login to complete the order');
  $form["login_pane"]['name']['#title'] = t('Username');
}
