<?php
/**
 * @file
 * kms_oci_queue.module
 * Handle query queues.
 *
 * @author Mikkel Jakobsen <mikkel@adapt.dk>
 */

define('KMS_OCI_QUEUE_PREFIX', 'kms_oci_queue');
define('KMS_OCI_QUEUE_ENGINE_ROOT_URI', 'public://' . KMS_OCI_QUEUE_PREFIX);
define('KMS_OCI_QUEUE_ENGINE_DIR_JOBS', 'jobs');
define('KMS_OCI_QUEUE_ENGINE_DIR_JOBS_PROCESSED', 'jobs_processed');
define('KMS_OCI_QUEUE_ACTION_USER_INSERT', 'user_insert');
define('KMS_OCI_QUEUE_ACTION_BUNDLE_SAVE', 'bundle_save');
define('KMS_OCI_QUEUE_ACTION_BUNDLE_DELETE', 'bundle_delete');
define('kMS_OCI_QUEUE_DEBUG', TRUE);

/**
 * Implements hook_menu().
 */
function kms_oci_queue_menu() {
  $items = array();
  $items['admin/reports/kms-oci-queue'] = array(
    'title' => 'Oci queue status',
    'description' => 'Show oci queue status',
    'page callback' => 'kms_oci_queue_admin_page',
    'access arguments' => array('administer kms oci queue'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['kms-oci-queue/ajax/load-log/%'] = array(
    'title' => 'Show job log',
    'page callback' => 'kms_oci_queue_admin_page_ajax_job_log',
    'access arguments' => array('access content'),
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
  );
  $items['kms-oci-queue/ajax/load-statuses'] = array(
    'title' => 'Show job log',
    'page callback' => 'kms_oci_queue_admin_page_ajax_job_statuses',
    'access arguments' => array('access content'),
//    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_ctools_plugin_type().
 */
function kms_oci_queue_ctools_plugin_type() {
  return array(
    'queue_runner' => array(
      'use hooks' => FALSE,
    ),
  );
}

//// Define custom cron functions
//function kms_oci_queue_cronapi($op, $job = NULL) {
//  switch($op) {
//    case 'list':
//      return array(
//        'kms_oci_queue_query_creator_run' => 'Kms oci queue: Run query creator',
//      );
//
//    case 'rule':
//      switch($job) {
//        case 'kms_oci_queue_query_creator_run': return '1 * * * *';
//        break;
//      }
//      break;
//
//    case 'execute':
//      switch($job) {
//        case 'kms_oci_queue_query_creator_run':
//          kms_oci_queue_query_creator_run();
//          break;
//      }
//      break;
//  }
//
//}

function kms_oci_queue_cron() {
  // Atodo: Do this as a cron queue instead.
  kms_oci_queue_query_creator_run();
}

/**
 * Implements hook_cron_queue_info().
 */
function kms_oci_queue_cron_queue_info() {
//  $queues['kms_oci_queue_query_creator'] = array(
//    'worker callback' => 'kms_oci_queue_query_creator_run',
//    'time' => 120,
//  );
  $queues['kms_oci_queue_query'] = array(
    'worker callback' => 'kms_oci_queue_query_run',
    'time' => 120,
  );
  return $queues;
}

/**
 * Process a job queue item of the query creator queue.
 */
function kms_oci_queue_query_creator_run() {
  // Load query creator queue.
  $creator_queue = DrupalQueue::get(
    KmsOciQueueJob::$queues['creator']['name'],
    TRUE
  );
  // Load query executor queue.
  $exe_queue = DrupalQueue::get(
    KmsOciQueueJob::$queues['executor']['name'],
    TRUE
  );
  // Get query creator item.
  $item = $creator_queue->claimItem();
  // Find job id.
  $jid = $item->item_id;
  // Creator item with data to create query queue.
  $creator_item = $item->data;
  // We need parameters in order to create queries.
  if (empty($creator_item->params)) {
    return;
  }
  // Do not need original item anymore.
  unset($item);

  // Create executor queue items via ctools plugins.
  ctools_include('plugins');
  $plugins = ctools_get_plugins('kms_oci_queue', 'queue_runner');
  $line_num = 0;
  array_walk(
    $plugins,
    function($plugin) use ($jid, $creator_item, $exe_queue, &$line_num) {
    // Only load plugins corresponding to the queue item action.
    if ($plugin['type'] != $creator_item->action) {
      return;
    }
    // Get proper plugin function in order to create executor items.
    if ($function = ctools_plugin_get_function($plugin, 'query_creator_run')) {
      $line_num = $function($jid, $creator_item, $exe_queue);
    }
  });

  // If line number is returned from plugin(s) then write it in log.
  if ($line_num) {
    KmsOciQueueJob::log(
      $jid,
      '%line_num lines to be written in job file.',
      array('%line_num' => $line_num)
    );
  }

}

/**
 * Process a job queue item of the query queue.
 *
 * @param object $item
 *   Queue item object.
 */
function kms_oci_queue_query_run($item) {
  // Load query queue executor plugins to create sql output.
  ctools_include('plugins');
  $plugins = ctools_get_plugins('kms_oci_queue', 'queue_runner');
  $output = '';
  array_walk($plugins, function($plugin) use ($item, &$output) {
    // Only load plugins corresponding to the queue item action.
    if ($plugin['type'] != $item->action) {
      return;
    }
    // Accumulate output.
    if ($function = ctools_plugin_get_function($plugin, 'query_run')) {
      $output .= $function($item);
    }
  });
  // If no output return (do nothing).
  if (empty($output)) {
    return;
  }
  // Write job (sql) file.
  $job = KmsOciQueueJobFactory::get($item->jid);
  $filename = $job->jid . '.job';
  $temp_name = sprintf('temporary://%s.tmp', $job->jid);
  $dest_name = implode(
    '/',
    array(
      KMS_OCI_QUEUE_ENGINE_ROOT_URI,
      KMS_OCI_QUEUE_ENGINE_DIR_JOBS,
      $filename,
    )
  );
  // Append output to tmp file.
  if (file_put_contents($temp_name, $output, FILE_APPEND) === FALSE) {
    $job->changeStatus(
      KmsOciQueueJob::STATUS_FAILED,
      'File creation failed. Could not write to tmp dir.'
    );
  }
  // If last line has been written move tmp file to actual destination dir.
  elseif ($item->is_last_item) {
    $move = file_unmanaged_move($temp_name, $dest_name, FILE_EXISTS_REPLACE);
    if ($move) {
      $job->changeStatus(
        KmsOciQueueJob::STATUS_WAITING,
        'File creation succeeded. Saved in %filepath',
        array('%filepath' => $move)
      );
    }
    else {
      $job->changeStatus(
        KmsOciQueueJob::STATUS_FAILED,
        'File creation failed. Cannot move filename from tmp dir.'
      );
    }

  }
}

/**
 * Get all current job ids.
 *
 * @return array
 *   Array of all current job ids.
 */
function kms_oci_queue_get_job_ids() {
  $result = db_select('kms_oci_queue_job', 'j')->fields('j', array('jid'))->execute()->fetchCol();
  return $result ?: array();
}

/**
 * Show Kms oci report page.
 *
 * @return array
 *   Render array.
 */
function kms_oci_queue_admin_page () {
  drupal_add_library('system', 'jquery.cookie');
  drupal_add_js(drupal_get_path('module', 'kms_oci_queue') . '/js/kms_oci_queue_reports.js');
  drupal_add_css(drupal_get_path('module', 'kms_oci_queue') . '/css/kms_oci_queue_reports.css');

  $output['queues'] = kms_oci_queue_admin_page_jobs();
  return $output;
}

/**
 * Render table with kms oci jobs.
 *
 * @return array
 *   Render array.
 */
function kms_oci_queue_admin_page_jobs () {
  $output = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array('kms-oci-queue-jobs-overview'),
    ),
  );

  $jobs_output = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array('kms-oci-queue-jobs'),
    ),
  );
  $jobs_output["job_queue_title"] = array(
    '#type' => 'html_tag',
    '#tag' => 'h2',
    '#value' => t('Jobs'),
  );
  $rows = array();
  foreach (kms_oci_queue_get_job_ids() as $jid) {
    $job = KmsOciQueueJobFactory::get($jid);
    $job_info = $job->info . ' [<a href="#" class="more">' . t('info') . '</a>]';
    $rows[] = array(
      'data' => array(
        array(
          'data' => $job->jid,
          'data-jid' => $job->jid,
          'class' => 'job-log-trigger',
        ),
        array(
          'data' => $job_info,
          'data-jid' => $job->jid,
          'class' => array('job-info'),
        ),
        array(
          'data' => $job->status->message,
          'data-jid' => $job->jid,
          'class' => array(
            'status',
            KmsOciQueueJob::cssClassStatus($job->status->status),
          ),
        ),
        array('data' => format_date($job->created)),
      ),
    );

    $options['job_info_beautytip_' . $job->jid] = array(
      'cssSelect' => 'td[data-jid="' . $job->jid .  '"].job-info .more',
      'trigger' => array(0 => 'mouseover', 1 => 'click'),
      'text' => $job->infoDetails,
      'width' => 350,
    );
    beautytips_add_beautytips($options);

    $rows[] = array(
      'class' => array('kms-oci-queue-job-log'),
      'data-jid' => $job->jid,
      'data' => array(
        array('data' => '&nbsp;', 'colspan' => 4),
      ),
    );
  }

  if (empty($rows)) {
    $rows[] = array(
      'data' => array(
        array('data' => t('There are currently no jobs.'), 'colspan' => 4),
      ),
    );
  }

  $jobs_output["job_queue"] = array(
    '#theme' => 'table',
    '#header' => array(t('Job id'), t('Info'), t('Status'), t('Created')),
    '#rows' => $rows,
  );

  $output["kms_oci_queue_jobs"] = $jobs_output;

  return $output;
}

/**
 * Print a log for a given job.
 * 
 * @param int $jid
 *   Job id
 */
function kms_oci_queue_admin_page_ajax_job_log($jid) {
  $json['html'] = '';
  $job = KmsOciQueueJobFactory::get($jid);
  if (!empty($job)) {
    $log = $job->getLog();
  }
  $output = array();
  if (!empty($log)) {
    foreach ($log as $lid => $entry) {
      $message_vars = unserialize($entry->variables);
      if (empty($message_vars) || !is_array($message_vars)) {
        $message_vars = array();
      }
      $classes = array(KmsOciQueueJob::cssClassSeverity($entry->severity));
      $rows[] = array(
        array(
          'data' => format_date($entry->timestamp),
          'colspan' => 1,
          'class' => $classes,
        ),
        array(
          'data' => format_string($entry->message, $message_vars),
          'colspan' => 2,
          'class' => $classes,
        ),
      );
    }
    $output["log_$lid"] = array(
      '#theme' => 'table',
      '#header' => array(),
      '#rows' => $rows,
    );
    $json['html'] = render($output);
  }

  drupal_json_output($json);
  exit;
}

/**
 * Load statuses of the different jobs and print them as table cells.
 * Prints a json object with a structure like: job id => td table cell (html).
 */
function kms_oci_queue_admin_page_ajax_job_statuses() {
  $status = array();
  foreach (kms_oci_queue_get_job_ids() as $jid) {
    $job = KmsOciQueueJobFactory::get($jid);
    $status[$jid] = _theme_table_cell(array(
      'data' => $job->status->message,
      'data-jid' => $job->jid,
      'class' => array(
        'status',
        KmsOciQueueJob::cssClassStatus($job->status->status),
      ),
    ));
  }
  drupal_json_output(array(
    'status' => $status,
  ));
  exit;
}