;addressfield
projects[addressfield][subdir] = "contrib"
projects[addressfield][version] = "1.0-beta3"

;admin_menu
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc3"

;admin_views
projects[admin_views][subdir] = "contrib"
projects[admin_views][version] = "1.0"

;boolean
projects[boolean][subdir] = "contrib"
projects[boolean][version] = "1.0"

;commerce
projects[commerce][subdir] = "contrib"
projects[commerce][version] = "1.4"

;commerce_autosku
projects[commerce_autosku][subdir] = "contrib"
projects[commerce_autosku][version] = "1.1"

;commerce_extra
projects[commerce_extra][subdir] = "contrib"
projects[commerce_extra][version] = "1.0-alpha1"

;commerce_file
projects[commerce_file][subdir] = "contrib"
projects[commerce_file][version] = "1.0-beta4"

;commerce_vbo_views
projects[commerce_vbo_views][subdir] = "contrib"
projects[commerce_vbo_views][version] = "1.2"

;ctools
projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.2"

;date
projects[date][subdir] = "contrib"
projects[date][version] = "2.6"

;devel
projects[devel][subdir] = "contrib"
projects[devel][version] = "1.3"

;email
projects[email][subdir] = "contrib"
projects[email][version] = "1.2"

;entity
projects[entity][subdir] = "contrib"
projects[entity][version] = "1.0-rc3"

;features
projects[features][subdir] = "contrib"
projects[features][version] = "1.0"

;field_group
projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.1"

;field_permissions
projects[field_permissions][subdir] = "contrib"
projects[field_permissions][version] = "1.0-beta2"

;filefield_paths
projects[filefield_paths][subdir] = "contrib"
projects[filefield_paths][version] = "1.0-beta3+4-dev"

;filefield_sources
projects[filefield_sources][subdir] = "contrib"
projects[filefield_sources][version] = "1.7"

;hierarchical_select
projects[hierarchical_select][subdir] = "contrib"
projects[hierarchical_select][version] = "3.0-alpha5+9-dev"

;honeypot
projects[honeypot][subdir] = "contrib"
projects[honeypot][version] = "1.13"

;imce
projects[imce][subdir] = "contrib"
projects[imce][version] = "1.5"

;imce_mkdir
projects[imce_mkdir][subdir] = "contrib"
projects[imce_mkdir][version] = "1.0"

;imce_wysiwyg
projects[imce_wysiwyg][subdir] = "contrib"
projects[imce_wysiwyg][version] = "1.0"

;jquery_update
projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.2"

;libraries
projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.0"

;link
projects[link][subdir] = "contrib"
projects[link][version] = "1.0"

;masquerade
projects[masquerade][subdir] = "contrib"
projects[masquerade][version] = "1.0-rc5"

;menu_block
projects[menu_block][subdir] = "contrib"
projects[menu_block][version] = "2.3"

;menu_per_role
projects[menu_per_role][subdir] = "contrib"
projects[menu_per_role][version] = "1.x-dev"

;menu_position
projects[menu_position][subdir] = "contrib"
projects[menu_position][version] = "1.1"

;metatag
projects[metatag][subdir] = "contrib"
projects[metatag][version] = "1.0-beta2"

;migrate
projects[migrate][subdir] = "contrib"
projects[migrate][version] = "2.4"

;references
projects[references][subdir] = "contrib"
projects[references][version] = "2.0"

;oracle
projects[oracle][subdir] = "contrib"
projects[oracle][version] = "1.12"

;panels
projects[panels][subdir] = "contrib"
projects[panels][version] = "3.3"

;pathauto
projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

;pm_existing_pages
projects[pm_existing_pages][subdir] = "contrib"
projects[pm_existing_pages][version] = "1.4"

;querypath
projects[querypath][subdir] = "contrib"
projects[querypath][version] = "2.1"

;relation
projects[relation][subdir] = "contrib"
projects[relation][version] = "1.0-rc4"

;rules
projects[rules][subdir] = "contrib"
projects[rules][version] = "2.2"

;securepages
projects[securepages][subdir] = "contrib"
projects[securepages][version] = "1.x-dev"

;sharedemail
projects[sharedemail][subdir] = "contrib"
projects[sharedemail][version] = "1.x-dev"

;simplehtmldom
projects[simplehtmldom][subdir] = "contrib"
projects[simplehtmldom][version] = "1.12"

;smtp
projects[smtp][subdir] = "contrib"
projects[smtp][version] = "1.0-beta2"

;taxonomy_csv
projects[taxonomy_csv][subdir] = "contrib"
projects[taxonomy_csv][version] = "5.10"

;token
projects[token][subdir] = "contrib"
projects[token][version] = "1.4"

;views
projects[views][subdir] = "contrib"
projects[views][version] = "3.5"

;views_bulk_operations
projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.0"

;wysiwyg
projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"

