<?php
/**
 * @file
 * kms_permissions_ftp.module
 * Handle FTP folder permissions for users.
 *
 * @author Linas Balke <linas@adapt.dk>
 */

define('KMS_FTP_STRUCTURE_DIR', '/data3/Statsaftalen');
define('KMS_FTP_SCRIPT_CALL1', 'ssh -i  $HOME/.ssh/updateftpservers loadftp1.kmsext.dk');
define('KMS_FTP_SCRIPT_CALL2', 'ssh -i  $HOME/.ssh/updateftpservers loadftp2.kmsext.dk');

/**
 * Implements hook_menu().
 */
function kms_permissions_ftp_menu() {
  $items = array();

  $items['kms/ftp/read'] = array(
    'title' =>'FTP read',
    'description' => 'Scandir from ftp',
    'page callback' => 'kms_permissions_ftp_scan_store_structure',
    'access arguments' => array('ftp read'),
  );
  return $items;
}

/**
* Implements hook_field_widget_info().
*/
function kms_permissions_ftp_field_widget_info() {
  return array(
    'kms_ftp_permissions' => array(
      'label' => t('KMS FTP permissions'),
      'field types' => array('list_text'),
      'settings' => array(),
      'behaviors' => array(
        'multiple values' => FIELD_BEHAVIOR_CUSTOM,
      ),
    )
  );
}

/**
* Implements hook_field_widget_form().
*/
function kms_permissions_ftp_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {

  $value_key = key($field['columns']);
  $type = str_replace('options_', '', $instance['widget']['type']);
  $multiple = $field['cardinality'] > 1 || $field['cardinality'] == FIELD_CARDINALITY_UNLIMITED;
  $required = $element['#required'];
  $has_value = isset($items[0][$value_key]);
  $properties = _options_properties($type, $multiple, $required, $has_value);
  $instance_settings = $instance['widget']['settings'];

      $default_value = array();

      if (is_array($items)) {
        // Put current field values in
        foreach ($items as $key => $item) {
          $default_value[] = $item['value'];
        }
      }

      $options = kms_permissions_ftp_widget_options($instance_settings);

      $element += array(
        '#type' => $multiple ? 'checkboxes' : 'radios',
        '#title' => (t('kms_ftp_permissions')),
        '#default_value' => $default_value,
        '#options' => $options
      );

  $element += array(
    '#value_key' => $value_key,
    '#element_validate' => array('options_field_widget_validate'),
    '#properties' => $properties,
  );

  return $element;
}

/**
* Implements hook_field_widget_error().
*/
function kms_permissions_ftp_field_widget_error($element, $error) {
  form_error($element, $error['message']);
}

/**
 * Connect to oracle db and get applications or services.
 * @param string $type - type of option list to get
 */
function kms_permissions_ftp_widget_options($instance_settings) {

  $options = array();
  static $options;

  $rows = kms_permissions_ftp_scan_structure();

  if (!empty($rows)) {
    sort($rows);

    foreach($rows as $k=>$value) {
      $html = _kms_permissions_format_item_list_item($k, $value, 'ftp');
      $options[$k] = $html;
    }
  }

  return $options;
}

/**
 * Store the structure of the folders.
 */
function kms_permissions_ftp_scan_store_structure() {

  $rows = kms_permissions_ftp_scan_structure();
  sort($rows);

  if (!empty($rows)) {
    db_query("DELETE from kms_permissions_ftp_folders;");
    foreach($rows as $k=>$value) {
      $data = array(
        'fid' => $k,
        'name' => $value
      );

      drupal_write_record('kms_permissions_ftp_folders', $data);
    }
  }
}

/**
 * Read the structure of the folders. Ret
 * @return alphabetically sorted array of folders
 */
function kms_permissions_ftp_scan_structure() {
  // Set the dir to read from
  is_dir(KMS_FTP_STRUCTURE_DIR) ? $folders = scandir(KMS_FTP_STRUCTURE_DIR): $folders = array();

  return $folders;
}

/**
 * Implements hook_user_presave().
 */
function kms_permissions_ftp_entity_presave($entity) {
  $lang = field_language('user', $entity, 'field_ftp_permissions');

  if(!empty($entity->field_ftp_permissions)) {
    if($entity->field_ftp_permissions[$lang] !== $entity->original->field_ftp_permissions[$lang]){
      watchdog('Permissions FTP', 'Change has been triggered in FTP permissions for individual user', array(), WATCHDOG_NOTICE);
      variable_set('kms_ftp_perm_change', TRUE);
    }
  }
}

/**
 * Cron hook
 */
function kms_permissions_ftp_cron(){
  kms_permissions_ftp_scan_store_structure();

  if (variable_get('kms_ftp_perm_change')){
    //Trigger external script
    shell_exec(KMS_FTP_SCRIPT_CALL1);
    shell_exec(KMS_FTP_SCRIPT_CALL2);
    // Set variable to false, as script should revisit the view and update things accordingly
    variable_set('kms_ftp_perm_change', FALSE);
    watchdog('Permissions FTP', 'External bash script initiated by cron run', array(), WATCHDOG_NOTICE);
  }
}

/**
 * Return nicely formatted array of ftp permissions associated with a bundle.
 */
function _kms_permissions_ftp_get_permissions_by_bid($bid, &$permissions = array()) {
  $bundle = node_load($bid);
  // FTP permissions
  $field_ftp_permissions = field_get_items('node', $bundle, 'field_ftp_permissions');
  if (!empty($field_ftp_permissions)) {
    foreach ($field_ftp_permissions as $ftp_permissions) {
      $permissions['ftp']['a' . $ftp_permissions['value']] = array(
        'id' => $ftp_permissions['value'],
      );
    }
  }

  return $permissions;
}
