<?php

function kms_iframe_ctools_render_alter(&$info, &$page, &$context){

  // Add iframe css if the page is iframed
  if (kms_iframe_test()) {
    $url = variable_get('kms_iframe_url', 'http://kortforsyningen.dev');
    drupal_add_css(drupal_get_path('theme', 'kms') . '/css/iframe.css');
    drupal_add_http_header('X-Frame-Options', 'ALLOW-FROM ' . $url);

    $path = drupal_get_path('module', 'kms_iframe');
    drupal_add_js($path . '/js/iframeResizer.contentWindow.min.js', array('weight' => 1));
  }
}


function kms_iframe_url_outbound_alter(&$path, &$options, $original_path) {

  // If the page is not iframed return
  if (!kms_iframe_test()) {
    return;
  }

  // Append /iframe to urls starting with edit/profile when in an iframe
  if (strpos($path, 'edit/profile') === 0) {
    $path .= '/iframe';
  }

  // Redirect to edit/profile when logging out
  if (strpos($path, 'user/logout') === 0) {
    $options['query']['destination']  = 'edit/profile/iframe'; 
  }

  // Redirect to edit/profile when logging out
  if (strpos($path, 'user/register') === 0) {
    $path = 'add/profile/iframe';
    $options['query']['destination']  = 'edit/profile/iframe';
  }

  // Redirect to edit/profile when logging out
  if (strpos($path, 'user/password') === 0) {
    $path = 'edit/profile/password/iframe';
    $options['query']['destination']  = 'edit/profile/iframe';
  }

}

/**
 * Check if the current path ends with iframe
 */
function kms_iframe_test() {
  $path = current_path();
  $match = 'iframe';

  if (substr_compare($path, $match, strlen($path)-strlen($match), strlen($match)) === 0) {
    return true;
  }

  return false;

}
