<?php
return array(
  'Beskæftigelsesministeriet' => array(
    'Andet',
    'Arbejdsmarkedets Erhvervssygdomssikring (AES)',
    'Arbejdsmarkedsstyrelsen',
    'Arbejdsmiljørådet',
    'Arbejdsretten',
    'Branchearbejdsmiljøråd',
    'CABI - Center for Aktiv BeskæftigelsesIndsats',
    'Departement',
    'Beskæftigelsesrådet',
    'Beskæftigelsesankenævn',
    'Arbejdsskadestyrelsen',
    'Arbejdstilsynet',
    'ATP-Ankenævnet',
    'Det Grønlandske Arbejdsmiljøråd',
    'Det Grønlandske Nævn for Arbejdsskadesikring',
    'Tilsynsrådet for tilsyn med a-kasser og kommuner',
    'Styrelsen for Fastholdelse og Rekruttering',
    'Forligsinstitutionen',
    'Det Nationale Forskningscenter for Arbejdsmiljø (NFA)',
    'Erhvervssygdomsudvalget'
  ),
  'Erhvervs- og Vækstministeriet' => array(
    'Andet',
  	'Ankenævnet for Investeringsforeninger',
  	'Ankenævnet for Køreundervisning',
  	'Ankenævnet for Patenter og Varemærker',
  	'Ankenævnet for hotel, restaurant og turisme',
  	'Ankenævnet for Forsikring',
  	'Ankenævnet for Bus, Tog og Metro',
  	'Ankenævnet for Feriehusudlejning',
  	'Ankenævnet for Fondsmæglerselskaber',
  	'Ankenævnet for Tekniske Installationer',
  	'Ankenævnet på Energiområdet',
  	'Danmarks Vækstråd',
  	'Dansk Design Center - DDC',
  	'Departement',
  	'Danmarks Skibskredit A/S',
  	'Danmarks Nationalbank',
  	'Ankenævn for Dyrlæger',
  	'Arkitektnævnet',
  	'Byggeriets Ankenævn',
  	'Ankenævnet for Bedemandsbranchen',
  	'Aktieselskaber mv. med statslig deltagelse',
  	'Det finansielle Kontaktudvalg',
  	'Det Finansielle Virksomhedsråd',
  	'Penge- og Pensionspanelet',
  	'Realkreditankenævnet',
  	'Regnskabsrådet',
  	'Pengeinstitutankenævnet',
  	'Patent- og Varemærkestyrelsen',
  	'Lodsrådet',
  	'Lodstilsynet',
  	'Pakkerejse-Ankenævnet',
  	'Revisorkommissionen',
  	'Revisornævnet',
  	'Søfartsstyrelsen',
  	'Sølovsudvalget',
  	'Søsportens Sikkerhedsråd',
  	'Søfartens Arbejdsmiljøråd',
  	'Skibstilsynsrådet',
  	'Revisortilsynet',
  	'Sikkerhedsstyrelsen',
  	'Skibsfartsnævnet',
  	'Landsbevillingsnævnet',
  	'Konkurrencerådet',
  	'Finansiel Stabilitet A/S',
  	'Finanstilsynet',
  	'Fondsrådet',
  	'ETA-Danmark A/S',
  	'Erhvervsstyrelsen',
  	'Det Tekniske Sikkerhedsråd',
  	'Dispachørkommissionen',
  	'Erhvervsankenævnet',
  	'Forbrugerforum',
  	'Forbrugerklagenævnet',
  	'Klagenævnet for Udbud',
  	'Konkurrenceankenævnet',
  	'Konkurrence- og Forbrugerstyrelsen',
  	'Klagenævnet for Ejendomsformidling',
  	'Helbredsnævnet for Søfarende og Fiskere',
  	'Forbrugerombudsmanden',
  	'Håndværkets Ankenævn',
  	'Specialudvalget vedrørende den Europæiske Bank for Genopbygning og Udvikling (EBRD)',
  	'Stormrådet',
  	'Voldgiftsnævnet for bygge- og anlægsvirksomhed',
  	'Uddannelsesrådet for de Maritime Uddannelser',
  	'VisitDenmark',
  	'Teleankenævnet',
  	'Translatørkommissionen'
  ),

'Finansministeriet' => array(	
  'Andet',
  'Statens It',
  'Statens Samarbejdsnævn',
  'Tjenestemandsretten',
  'Statens Center for Kompetenceudvikling',
  'Statens Administration',
  'Moderniseringsstyrelsen',
  'Nævnet for Helbredsbedømmelser i Tjenestemandssager',
  'SKI - Statens og Kommunernes Indkøbs Service A/S',
  'Lønningsrådet',
  'Air Greenland A/S',
  'Aktieselskaber mv. med statslig deltagelse',
  'Københavns Lufthavne A/S',
  'Danske Spil A/S',
  'Freja ejendomme A/S',
  'Kammeradvokaten',
  'DONG Energy A/S',
  'Digitaliseringsstyrelsen',
  'Departement',
  'Det Danske Klasselotteri A/S'
),

'Forsvarsministeriet' => array(	
   'Andet',
   'Særstatusområde Christiansø',
   'Værnepligtsnævnet',
   'Isbrydningsrådet',
   'Hjemmeværnskommandoen',
   'Forsvarskommandoen',
   'Forsvarsministeriets Interne Revision',
   'Hjemmeværnets distriktsudvalg',
   'Forsvarets Koncernfælles Informatiktjeneste',
   'Forsvarets Efterretningstjeneste',
   'Disciplinarnævn i henhold til lov om værnepligtens opfyldelse ved civilt arbejde',
   'Forsvarets Auditørkorps',
   'Forsvarets Bygnings- og Etablissementstjeneste',
   'Disciplinarnævn i henhold til Beredskabsloven',
   'Departement',
   'Ankenævnet for disciplinarmidler i henhold til Beredskabsloven',
   'Ankenævnet for disciplinarmidler i henhold til lov om værnepligtens opfyldelse ved civilt arbejde',
   'Beredskabsstyrelsen'
),

'Justitsministeriet' => array(
  'Retslægerådet',
  'Andet',
  'Retsplejerådet',
  'Retspsykiatrisk Klinik',
  'Rådet for Sikker Trafik',
  'Pressenævnet',
  'Færdselssikkerhedskommissionen',
  'Flygtningenævnet',
  'Konkursrådet',
  'Rigsadvokaten',
  'Rigspolitichefen',
  'Wamberg-udvalget',
  'Udlændingestyrelsen',
  'Statens Våbenkontrol',
  'Straffelovrådet',
  'Tilsynsrådet vedrørende beskæftigelsen af de indsatte i kriminalanstalterne',
  'Erstatningsnævnet',
  'Dyreværnsrådet',
  'Advokatsamfundet',
  'Det Dyreetiske Råd',
  'Det Kriminalpræventive Råd',
  'Direktoratet for Kriminalforsorgen',
  'Departement',
  'Den Uafhængige Politiklagemyndighed',
  'Civilstyrelsen',
  'Datatilsynet',
),

'Klima-, Energi- og Bygningsministeriet' => array(
  'Andet',
  'Aktieselskaber mv. med statslig deltagelse',
  'Bygningsstyrelsen',
  'Danmarks Meteorologiske Institut - DMI',
  'Energistyrelsen',
  'Energitilsynet',
  'Nordsøenheden',
  'Energinet.dk',
  'Energiklagenævnet',
  'De Kgl. Bygningsinspektører',
  'De Nationale Geologiske Undersøgelser for Danmark og Grønland - GEUS',
  'Departement',
),

'Kulturministeriet' => array(
   'Nota - Nationalbibliotek for mennesker med læsevanskeligheder',
	 'Andet',
	 'Ophavsretslicensnævnet',
	 'Ordrupgaard',
	 'Nationalmuseet',
	 'Medierådet for Børn og Unge',
	 'Landsdelsorkestre',
	 'Landsdelsscener',
	 'Litteraturudvalget',
	 'Overgaden - Institut for Samtidskunst',
	 'Rådet for Zoologiske Anlæg',
	 'Statens Kunstfond',
	 'Statens Kunstråd',
	 'Statens Museum for Kunst',
	 'Statens Forsvarshistoriske Museum',
	 'Statens Arkiver',
	 'Radio- og tv-nævnet',
	 'Rytmisk Musikkonservatorium',
	 'Skuespillerskolen ved Aarhus Teater',
	 'KVINFO Center for information om kvinde- og kønsforskning',
	 'Kunsthåndværk- og Designudvalget',
	 'Film- og Scenekunstudvalget',
	 'Forfatterskolen',
	 'Idrættens Analyseinstitut',
	 'Dramatikeruddannelsen',
	 'DR',
	 'Det Kongelige Danske Kunstakademi, Billedkunstskolerne',
	 'Det Kongelige Teater',
	 'Det Særlige Bygningssyn',
	 'Københavns Teater',
	 'Kulturministeriets Forskningsudvalg',
	 'Kulturstyrelsens fagligt rådgivende udvalg for Udviklingspuljen for folke- og skolebiblioteker, RUF',
	 'Kulturværdiudvalget',
	 'Kunsthal Charlottenborg',
	 'Kulturstyrelsen',
	 'Kulturministeriets Udvalg for Idrætsforskning',
	 'Kulturministeriets Sikringsudvalg',
	 'Kulturministeriets Tidsskriftstøtteudvalg',
	 'Statens Teaterskole',
	 'Statens Værksteder for Kunst',
	 'Teatercentrum',
	 'Tonekunstudvalget for Klassisk Musik',
	 'Tonekunstudvalget for Rytmisk Musik',
	 'Syddansk Musikkonservatorium & Skuespillerskole',
	 'Styrelsen for Slotte og Kulturejendomme',
	 'Statsbiblioteket',
	 'Statsstøttede museer (særligt tilskud)',
	 'Stednavneudvalget',
	 'TV 2/DANMARK A/S',
	 'Udvalget for Kunst i det Offentlige Rum',
	 'Zoologiske anlæg',
	 'Ugeavispuljens fordelingsudvalg',
	 'Udvalget vedrørende Tilgængelighedspraksis',
	 'Udvalget til fordeling af rådighedsbeløb for billedkunst',
	 'Udvalget til fordeling af rådighedsbeløb for grammofonplader mv.',
	 'Det Kongelige Bibliotek Nationalbibliotek og Københavns Universitetsbibliotek',
	 'Det Kongelige Akademi for de Skønne Kunster',
	 'Den Hirschsprungske Samling',
	 'Den Jyske Opera',
	 'Departement',
	 'Den Danske Filmskole',
	 'Dansk Sprognævn',
	 'Dansens Hus',
	 'Dansk Jagt- og Skovbrugsmuseum',
	 'Dansk Landbrugsmuseum',
	 'Det Billedkunstneriske Indkøbs- og Legatudvalg',
	 'Det Danske Filminstitut',
	 'Det Jyske Kunstakademi',
	 'Det Jyske Musikkonservatorium',
	 'Det Kgl. Danske Musikkonservatorium',
	 'Det fynske Kunstakademi',
	 'Det Danske Sprog- og Litteraturselskab',
	 'Det Danske Institut i Rom',
	 'Det Danske Kulturinstitut',
	 'Danmarks Kunstbibliotek',
	 'Danish Crafts - Informationscenter for dansk Kunsthåndværk',
	 'Centralbiblioteker',
	 'Dagbladsnævnet',
	 'Dagbladspuljens fordelingsudvalg',
	 'Biblioteksrådet',
	 'Biblioteksafgiftsnævnet',
	 'Anti Doping Danmark',
	 'Arkitekturudvalget',
),

'Miljøministeriet' => array(
  'Andet',
  'Landinspektørnævnet',
  'Miljømærkenævnet',
  'Miljøstyrelsen',
  'Kosmetikrådet',
  'Geodatastyrelsen',
  'Depotrådet',
  'Fredningsnævn',
  'Informationscenteret for Miljø & Sundhed',
  'Natur- og Miljøklagenævnet',
  'Naturstyrelsen',
  'Vildtforvaltningsrådet',
  'Samordningsudvalget vedrørende Infrastruktur for geografisk information',
  'Skovrådet',
  'Taksationskommissionen',
  'Departement',
  'Bekæmpelsesmiddelrådet',
),

'Ministeriet for By, Bolig og Landdistrikter' => array(
  'Andet',
	'Departement',
),
'Ministeriet for Børn og Undervisning' => array(
  'UNI-C Danmarks IT-center for uddannelse og forskning',
  'Andet',
  'Udvalget vedrørende danske kulturelle anliggender i Sydslesvig',
  'Tvistighedsnævnet',
  'Sorø Akademis Skole',
  'Studievalg centre',
  'Tipsungdomsnævnet',
  'Rådet for Voksen- og Efteruddannelse (VEU-rådet)',
  'Rådet for Mellemlange Videregående Uddannelser',
  'Europaskoler',
  'Folkehøjskoler',
  'Folkeuniversitetsnævnet',
  'Erhvervsskoler',
  'Erhvervsakademirådet',
  'Den frie Lærerskole',
  'Departement',
  'Efterskoler',
  'Herlufsholm Skole',
  'Husholdnings- og håndarbejdsskoler',
  'Rådet for de Grundlæggende Erhvervsrettede Uddannelser (REU)',
  'Rådet for de Gymnasiale Uddannelser',
  'Rådet for Evaluering og Kvalitetsudvikling af Folkeskolen',
  'Produktionsskoler',
  'Nævnet til Fremme af Debat og Oplysning om Europa',
  'Klagenævnet for vidtgående specialundervisning',
  'Kvalitets- og Tilsynsstyrelsen',
  'Den danske UNESCO-nationalkommission',
  'Dansk Center for Undervisningsmiljø',
  'Ankenævnet vedrørende Praktikvirksomheder',
  'Danmarks Evalueringsinstitut (EVA)',
),
'Ministeriet for Forskning, Innovation og Videregående Uddannelser' => array(
  'Andet',
  'ACE Denmark - Akkrediteringsinstitutionen',
  'Ankenævnet for Uddannelsesstøtten',
  'Arkitektskolen Aarhus',
  'Copenhagen Business School - Handelshøjskolen',
  'Danmarks Forskningspolitiske Råd',
  'Danmarks Medie- og Journalisthøjskole',
  'Danmarks Tekniske Universitet (DTU)',
  'Dansk Dekommissionering',
  'Det Administrative Bibliotek',
  'Det Danske Institut i Damaskus',
  'Det Danske Institut i Athen',
  'Det danske Studenterhus i Paris',
  'Det Europæiske Universitetsinstitut i Firenze',
  'Det Frie Forskningsråd',
  'Det Informationsvidenskabelige Akademi (IVA)',
  'Departement',
  'Designskolen Kolding',
  'Det Kongelige Danske Kunstakademis Skoler for Arkitektur, Design og Konservering',
  'Det Strategiske Forskningsråd',
  'Europæisk Center for Mindretalsspørgsmål (ECMI)',
  'IT-Universitetet i København',
  'It-vest',
  'Kommissionen for Videnskabelige Undersøgelser i Grønland (KVUG)',
  'Koordinationsudvalget for Forskning',
  'Københavns Universitet',
  'Lektoratsudvalget',
  'Maritime uddannelsesinstitutioner',
  'Niels Bohr Arkivet',
  'Nævnet om Støtteberettigende Uddannelser i Udlandet',
  'Professionshøjskoler',
  'Professionshøjskolernes Rektorkollegium',
  'Roskilde Universitet (RUC)',
  'Rådet for Internationalisering af Uddannelserne',
  'Rådet for Teknologi og Innovation',
  'Service 900-nævnet',
  'Studenterrådgivningen',
  'Styrelsen for Forskning og Innovation',
  'Styrelsen for International Uddannelse',
  'Styrelsen for Videregående Uddannelser og Uddannelsesstøtte',
  'SU-rådet',
  'Syddansk Universitet',
  'Teknologirådet',
  'Teleklagenævnet',
  'Udvalgene vedrørende Videnskabelig Uredelighed',
  'Universitets- og Bygningsstyrelsen',
  'Aalborg Universitet',
  'Aarhus Universitet',
),
'Ministeriet for Fødevarer, Landbrug og Fiskeri' => array(
  'Andet',
  'Danske Mejeriers Mælkeudvalg',
  'Det Økologiske Fødevareråd',
  'Det Rådgivende Udvalg for Fødevareforskning',
  'Det Veterinære Sundhedsråd',
  'Det danske FAO-Udvalg',
  'Det danske Codex Alimentarius Udvalg',
  'Departement',
  'Dyreforsøgstilsynet - Rådet for Dyreforsøg',
  'Erhvervsfiskeriudvalget',
  'Foderstofudvalget',
  'Fødevarestyrelsen',
  'Innovationsudvalget',
  'Klassificeringsudvalget for Svin, Kvæg og Får',
  'NaturErhvervstyrelsen',
  'Metodeudvalget',
  'Paragraf 2 udvalget',
  'Paragraf 5-udvalget fiskeri',
  'Paragraf 7-udvalget for Rekreativt Fiskeri, Ferskvandsfiskeri og Fiskepleje',
  'Plantenyhedsnævnet',
  'Rådet vedrørende hold af særlige dyr',
  'Udvalget for planter og plantesundhed',
  'Udvalget for plantesorter og udsæd',
  'Udvalget for Skovfrø og -planter',
  'Udvalget for Plantegenetiske Ressourcer',
  'Udvalget for gødning m.m.',
  'Udvalget for de af Plantedirektoratet autoriserede laboratorier',
),

'Ministeriet for Ligestilling og Kirke' => array(
  'Andet',
  'Kirkemusikskoler',
  'Folkekirkens uddannelsesinstitutioner',
  'Folkekirkens mellemkirkelige Råd',
  'Bestyrelsen for folkekirkens uddannelsesinstitutioner for præster',
  'Departement',
  'Folkekirken',
),

'Ministeriet for Sundhed og Forebyggelse' => array(
  'Andet',
  'Ankenævnet i sager om svangerskabsafbrydelse, fosterreduktion og sterilisation',
  'Bivirkningsrådet',
  'Voldgiftsnævnet vedrørende apoteksovertagelse',
  'Institutrådet ved Statens Serum Institut',
  'Kennedy Centret - Nationalt forsknings- og rådgivningscenter for genetik, synshandicap og mental ret',
  'Lægemiddelstyrelsen',
  'Farmakopinævnet',
  'Det Nationale Forebyggelsesråd',
  'Den Nationale Videnskabsetiske KomitÃ©',
  'Departement',
  'Det Etiske Råd',
  'Medicintilskudsnævnet',
  'National Sundheds-IT',
  'Statens Serum Institut',
  'Sundhedsstyrelsen',
  'Videns- og Forskningscenter for Alternativ Behandling',
  'Specialtandlægenævnet',
  'Registreringsnævnet',
  'Patientombuddet',
  'Psykiatriske Patientklagenævn',
),

'Skatteministeriet' => array(
  'Virksomhedskontaktudvalget',
  'Andet',
  'Skatterådet',
  'Det Eksterne Kontaktudvalg',
  'Landsskatteretten',
  'Skattecentre',
  'Departement',
),

'Social- og Integrationsministeriet' => array(
  'Andet',
  'SFI - Det Nationale Forskningscenter for Velfærd',
  'Socialstyrelsen',
  'Udbetaling Danmark',
  'Rådet for Socialt Udsatte',
  'Rådet for Etniske Minoriteter',
  'Møltrup Optagelseshjem',
  'Pensionsstyrelsen',
  'Psykolognævnet',
  'Ligebehandlingsnævnet',
  'ldreForum',
  'Arbejdsmiljøklagenævnet',
  'Børnerådet',
  'Center for frivilligt socialt arbejde',
  'Ankestyrelsens Beskæftigelsesudvalg',
  'Ankestyrelsen',
  'Adoptionsnævnet',
  'Center for Selvmordsforskning',
  'Den Uvildige Konsulentordning på Handicapområdet - DUKH',
  'Frivilligrådet',
  'Hjælpemiddelinstituttet',
  'Kofoeds Skole',
  'Døvefilm',
  'Det Centrale Handicapråd',
  'Departement',
  'De Sociale Nævn',
),

'Statsministeriet' => array(
  'Andet',
  'Departement',
  'Statsministeriet',
),

'Transportministeriet' => array(
  'Auditøren under Transportministeriet',
  'Andet',
  'Banedanmark',
  'Danmarks Vej- og Bromuseum',
  'Aktieselskaber mv. med statslig deltagelse',
  'Departement',
  'Departement',
  'Vejtransportrådet',
  'Kystdirektoratet',
  'Metroselskabet I/S',
  'Naviair',
  'Jernbanenævnet',
  'Havarikommissionen for Vejtrafikulykker',
  'Det statslige ekspropriationsvæsen',
  'DSB',
  'Havarikommissionen for Civil Luftfart og Jernbane',
  'Overtaksationskommissioner',
  'Post Danmark A/S',
  'Udviklingsselskabet By & Havn I/S',
  'Vejdirektoratet',
  'Vejregelrådet',
  'Trafikstyrelsen',
  'Taksationskommissioner (statslige)',
  'Sund & Bælt Holding A/S',
  'Taksationskommissioner (kommunale)',
),

'Udenrigsministeriet'	=> array(
  'Den humanitære kontaktgruppe',
  'Andet',
  'Departement',
  'Rådet for Internationalt Udviklingssamarbejde',
  'Dansk Center for Internationale Studier og Menneskerettigheder',
  'Danmarkshuset i Paris',
  'Center for Kultur og Udvikling',
  'Danidas Oplysningsudvalg',
  'Regeringens Røde Kors-Udvalg',
  'Rehabiliterings- og Forskningscentret for Torturofre (RCT)',
  'Styrelsen for Internationalt Udviklingssamarbejde',
  'Udvalget for Blandede Kreditter',
),

'Økonomi- og Indenrigsministeriet' => array(
  'Det Kommunale og Regionale Evalueringsinstitut (KREVI)',
  'Andet',
  'Kommunernes Lønningsnævn',
  'Kontaktudvalget for det Tyske Mindretal',
  'Departement',
  'De Økonomiske Råd',
  'Bestyrelsen for det Makroøkonomiske Modelarbejde (ADAM)',
  'Danmarks Statistik',
  'Statsforvaltninger',
  'Valgbarhedsnævnet',
  'Valgnævnet'
)
);