<?php
return array(
  'Beskæftigelsesministeriet' => array(
    'Arbejdstilsynet',
    'Departement',
    'Det Nationale Forskningscenter for Arbejdsmiljø',
    'Styrelsen for Arbejdsmarked og Rekruttering',
    'Andet',
   ),
  'Energi-, Forsynings- og Klimaministeriet' => array(
    'Departement',
    'DMI',
    'Energinet.dk',
    'Energistyrelsen',
    'Energitilsynet',
    'EUDP',
    'Geodatastyrelsen',
    'GEUS',
    'Klimarådet',
    'Styrelsen for Dataforsyning og Effektivisering',
    'Taksationsmyndigheden',
    'Teleklagenævnet',
    'Andet',
  ),
  'Erhvervs- og Vækstministeriet' => array(
    'Danpilot',
    'Dansk Standard',
    'Departement',
    'Design Society',
    'EKF Danmarks Eksportkredit',
    'Erhversstyrelsen',
    'Finanstilsynet',
    'Finasiel stabilitet',
    'Garantifonde',
    'Konkurrence- og Forbrugerstyrelsen',
    'Nordsøfonden',
    'Nævnenes hus',
    'Patent- og Varemærkestyrelsen',
    'Sikkerhedsstyrelsen',
    'Søfartsstyrelsen',
    'Visit Danmark',
    'Vækstfonden',
    'Andet',
  ),
  'Finansministeriet' => array(
    'Center for offentlig innovation',
    'De Økonomiske Råd',
    'Departement',
    'Digitaliseringsstyrelsen',
    'Moderniseringsstyrelsen',
    'Statens administration',
    'Statens IT',
    'Andet',
  ),
  'Folketinget' => array(
    'FolketingetsOmbudsmand',
    'Rigsrevisionen',
    'Statsrevisorerne',
    'Andet',
  ),
  'Forsvarsministeriet' => array(
    'Adjudantstab og Jagtkaptajn',
    'Beredskabsstyrelsen',
    'Departement',
    'Forsvaret',
    'Forsvarets Auditørkorps',
    'Forsvarets Efterretningstjeneste',
    'Forsvarsministeriets Ejendomsstyrelse',
    'Forsvarsministeriets Materiel- og Indkøbsstyrelse',
    'Forsvarsministeriets Personalestyrelse',
    'Forsvarsministeriets Regnskabsstyrelse',
    'Hjemmeværnet',
    'Værnsfælles Forsvarskommando',
    'Andet',
  ),
  'Justitsministeriet' => array(
    'Civilstyrelsen',
    'Danmarks Domstole',
    'Datatilsynet',
    'Den uafhængige Politiklagemyndighed',
    'Departement',
    'Kriminalforsorgen',
    'Rigsadvokaten',
    'Rigspolitiet',
    'Sekretariatet for Pressenævnet',
    'Tilsynet med Efterretningsvæsnet',
    'Andet',
  ),
  'Kirkeministeriet' => array(
    'Departement',
    'Andet',
  ),
  'Kulturministeriet' => array(
    'Departement',
    'Rigsarkivet',
    'Slots- og Kulturstyrelsen',
    'Andet',
  ),
  'Miljø- og Fødevareministeriet' => array(
    'Departement',
    'Energiklagenævnet',
    'Fødevarestyrelsen',
    'Klagecenter for Fødevarer, Landbrug og Fiskeri',
    'Kystdirektoratet',
    'Miljøstyrelsen',
    'Natur- og Miljøklagenævnet',
    'NaturEhverstyrelsen',
    'Naturstyrelsen',
    'Styrelsen for Vand- og Naturforvaltning',
    'Andet',
  ),
  'Ministeriet for Børn,Undervisning og Ligestilling' => array(
    'Departement',
    'Styrelsen for IT og Læring',
    'Styrelsen for Undervisning og Kvalitet',
    'Andet',
  ),
  'Skatteministeriet' => array(
    'Departement',
    'SKAT',
    'Skatteankestyrelsen',
    'Andet',
  ),
  'Social- og Indenrigsministeriet' => array(
    'Ankestyrelsen',
    'CPR',
    'Danmarks statistik',
    'Departement',
    'KORA',
    'SFI',
    'Socialstyrelsen',
    'Andet',
  ),
  'Statsministeriet' => array(
    'Departement',
    'Andet',
  ),
  'Sundheds- og Ældreministeriet' => array(
    'Departement',
    'Lægemiddelstyrelsen',
    'Sekretariatet for Etisk Råd og Den Nationale Videnskabsetiske komite',
    'Statens SerumInstitut',
    'Styrelsen for Patientsikkerhed',
    'Sundhedsdatastyrelsen',
    'Sundhedsstyrelsen',
    'Andet',
  ),
  'Transport- og Bygningsministeriet' => array(
    'Banedanmark',
    'Bygningsstyrelsen',
    'Departement',
    'Færdselsstyrelsen',
    'Trafik- og Byggestyrelsen',
    'Vejdirektoratet',
    'Andet',
  ),
  'Uddannelses- og Forskningsministeriet' => array(
    'Departement',
    'Styrelsen for Forskning og Innovation',
    'Styrelsen for Videregående Uddannelser',
    'Øvrige',
  ),
  'Udenrigsministeriet' => array(
    'Departement',
    'Andet',
  ),
  'Udlændinge-, Integrations-og Boligministeriet' => array(
    'Departement',
    'Sekretariatet for Flygtningenævnet',
    'Sekretariatet for Udlændingenævnet',
    'Styrelsen for International Rekruttering og Integration',
    'Udlændingestyrelsen',
    'Andet',
  )
);
